CREATE DATABASE IF NOT EXISTS ipro_db;
USE ipro_db;
DROP TABLE processes;

CREATE TABLE processes(
    ID INT NOT NULL AUTO_INCREMENT,
    TIME TEXT,
    MACHINE_ID TEXT,
    PROCESS_NAME TEXT,
    MEMORY_UTILIZATION INT,
    CPU_UTILIZATION INT,
    MEMORY_USED INT,
    THREADS INT,
    USER TEXT,
    PATH TEXT,
    PRIMARY KEY (ID)
);


--example data
INSERT INTO processes (TIME, MACHINE_ID, PROCESS_NAME, MEMORY_UTILIZATION, CPU_UTILZATION, MEMORY_USED, THREADS, USER, PATH) VALUES(
    "2022-01-01:12:45:01",
    "50999",
    "virus.exe",
     99,
     99,
     50,
     "brody",
     "C:/Users/Brody/Desktop/virus.exe"
);

SELECT * FROM processes;
